definitions:
  config:
    /hippo:configuration/hippo:workflows/default:
      /handle:
        hipposys:classname:
          operation: override
          type: string
          value: org.bloomreach.forge.reviewworkflow.repository.documentworkflow.DocumentReviewWorkflowImpl
        /frontend:renderer:
          /requests:
            plugin.class:
              operation: override
              type: string
              value: org.bloomreach.forge.reviewworkflow.cms.reviewedactions.request.ReviewRequestWorkflowPlugin
          /review:
            jcr:primaryType: frontend:plugin
            acceptReview.enabled: true
            cancelReview.enabled: true
            dropReview.enabled: true
            internal.assign.list.path: /content/documents/administration/review-workflow/internal-assign-list
            online.request.list.path: /content/documents/administration/review-workflow/online-review-list
            onlineRequestReview.enabled: false
            plugin.class: org.bloomreach.forge.reviewworkflow.cms.reviewedactions.ReviewRequestsWorkflowPlugin
            rejectReview.enabled: true
            requestReview.enabled: true
            multipleReviewRequests.enabled: false
            multipleReviewRequests.limit: 0
            wicket.id: ${item}
        /hipposys:config:
          documentHandleFactoryClass:
            operation: override
            type: string
            value: org.bloomreach.forge.reviewworkflow.repository.documentworkflow.ReviewWorkflowDocumentHandleFactory
          scxml-definition:
            operation: override
            type: string
            value: reviewworkflow
