definitions:
  config:
    /hippo:configuration/hippo:workflows/default/handle/frontend:renderer/review:
      onlineRequestReview.enabled: true
      multipleReviewRequests.enabled: true
      multipleReviewRequests.limit: 2
